### ISSUE TITLE
Supervisor installer on debian

### ISSUE THREAD

**Issue by dsmurl** [dsmurl/SystemController4#10]
Branch - SupervisorInstallerOnDebian 

---

There shall be a supervisor setup the will allow the code to be installed and a supervisor d script to manage the auto-starting of the wsgi process when the beagle bone starts.

**Comment by faisalraja** [comment]
Created pull request: https://github.com/dsmurl/DiySystemController4/pull/39

**Comment by dsmurl** [comment]
Looks good.  Thanks man!  I merged it.
