### ISSUE TITLE
Create Run Loop

### ISSUE THREAD

**Issue by dsmurl** [dsmurl/SystemController4#25]
Branch - CreateRunLoop

This is the running loop that checks runs the rules and updates digital out pin values.  I guess we can start with running the rules every second.  In the future there will be a settings page where the interval can be set from like 1 second to 10 seconds or somethings but that's in a different story.

**Comment by faisalraja** [comment]
Created pull request: https://github.com/dsmurl/DiySystemController4/pull/38

**Comment by dsmurl** [comment]
Done.  Completed and merged by Faisal in pull request #38
